user_input1 = input("What is your favorite animal?")
print("Wow! " + user_input1 + "? How cool!")
user_input2 = input("What noise do they make?")
print("So they make " + user_input2 + " noise? Sick!")
user_input3 = input("Where do they live?")
print("Oh! they live at " + user_input3 + "? Alright!")
user_input4 = input("What color is the animal?")
print("Their " + user_input4 + "? How pretty!")
user_input5 = input("What do they eat?")
print("They eat " + user_input5 + "? How weird...")