user_input1 = input("What is your favorite animal?")
print("Wow! " + user_input1 + "? How cool!")
user_input2 = input("What noise do they make?")
print("So they make " + user_input2 + " noise? Sick!")
user_input3 = input("Where do they live?")
print("Oh! they live at " + user_input3 + "? Alright!")
user_input4 = input("What color is the animal?")
print("Their " + user_input4 + "? How pretty!")
user_input5 = input("Is the animal a carnivore or an herbivore?")
print("So their a " + user_input5 + "? Awesome!")
user_input6 = input("What do they eat?")
print("They eat " + user_input6 + "? Gross...")
user_input7 = input("What does the animal do to defend themselves?")
print("They " + user_input7 + "? Alright.")
user_input8 = input("What is a fun fact about them?")
print( user_input8 + "? Sick!")
user_input9 = input("Can you or you can yo not, get them as a pet?")
print( user_input9 + "? dang, alright!")
user_input10 = input("Last question! Why do you like this animal?")
print("So you like them because " + user_input10 + "? How interesting...")
user_input11 = input("So, your favorite animal is " + user_input1 + "? And they make " + user_input2 + " noise? They also live at " + user_input3 + "? And they are colored " + user_input4 + "? I'm correct so far right?")
print( user_input11 + "? Alright! I'll continue: The animal is a " + user_input5 + "? And they eat " + user_input6 + "... Again, gross. And they defend themselves by " + user_input7 + "? And you said that " + user_input8 + "? And you " + user_input9 + " own them as a pet? And you like them because " + user_input10 + "? This... Is awesome! Thank you for taking this survey!")