Qone = input("Is Mr. Osowski awesome? Yes or No\n>")
print(Qone == "Yes")
Q2 = input("What does 5 + 5 equal to?\n>")
Q2 = int(Q2)
print(Q2 == 10)
Q3 = input("Is Elden Ring the best game ever made? Yes or No\n>")
print(Q3 == "Yes")
Q4 = input("How much baby oil did Diddy have?\n>")
Q4 = int(Q4)
print(Q4 == 1000)
Q5 = input("Are you awesome? Yes or Yes\n>")
print(Q5 == "Yes")